<a href="https://colab.research.google.com/github/jaybhuvaa/LLM/blob/main/Bigram.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
with open('woo.txt','r',encoding='utf-8') as f:
    text=f.read()
print(len(text))
print(text[:200])


232131
  DOROTHY AND THE WIZARD IN OZ

  BY

  L. FRANK BAUM

  AUTHOR OF THE WIZARD OF OZ, THE LAND OF OZ, OZMA OF OZ, ETC.

  ILLUSTRATED BY JOHN R. NEILL

  BOOKS OF WONDER WILLIAM MORROW & CO., INC. NEW


**Tokenizer**

Tokenization in Python is essentially splitting a phrase, sentence, paragraph, or an entire text document into smaller units, such as individual words or terms. Each of these smaller units are called tokens. The tokens could be words, numbers or punctuation marks.

In [ ]:
chars=sorted(set(text))
print(chars)
print(len(chars))

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']
81


**Encoding-Deconding**

string_to_int = {ch:i for i , ch in enumerate (chars)}:

This line creates a dictionary string_to_int where each character in the chars string is mapped to its corresponding index in the chars string. The enumerate() function provides both the index and the character from the chars string.

encode=lambda s:[string_to_int[c] for c in s]:

This line defines an anonymous function encode which takes a string s as input. It uses a list comprehension to iterate over each character c in the input string s, and for each character, it retrieves its corresponding integer value from the string_to_int dictionary and forms a list of these integer values.

In [ ]:
string_to_int = {ch:i for i , ch in enumerate (chars)}
int_to_string = {i:ch for i , ch in enumerate (chars)}
encode=lambda s:[string_to_int[c] for c in s]
decode=lambda l:''.join([int_to_string[i] for i in l])

print(encode('Hello'))
print(encode('Jay'))
print(decode([32, 58, 65]))

[32, 58, 65, 65, 68]
[34, 54, 78]
Hel


**PyTorch**

PyTorch is an open source machine learning (ML) framework based on the Python programming language and the Torch library. Torch is an open source ML library used for creating deep neural networks and is written in the Lua scripting language. It's one of the preferred platforms for deep learning research. The framework is built to speed up the process between research prototyping and deployment.

In [ ]:
import torch
data=torch.tensor(encode(text),dtype=torch.long)
print(data[:100])

tensor([80,  1,  1, 28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,
         1, 47, 33, 50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0,  1,  1, 26,
        49,  0,  0,  1,  1, 36, 11,  1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,
         0,  0,  1,  1, 25, 45, 44, 32, 39, 42,  1, 39, 30,  1, 44, 32, 29,  1,
        47, 33, 50, 25, 42, 28,  1, 39, 30,  1, 39, 50,  9,  1, 44, 32, 29,  1,
        36, 25, 38, 28,  1, 39, 30,  1, 39, 50])


**Test-Validation Split**

> Why to split data?

  if we give model our full data to train than there is no any
    prediction part. it will be only factual data that will be given by model.
    
 if we split the data than model will be train based on the taining data anf to test the accuracy we can use the test data to check weather the model is doing right or wrong.
  



In [ ]:
n=int(0.8*len(data))
train_data=data[:n]
val_data=data[n:]
print(train_data[:10])
print(val_data[:10])

tensor([80,  1,  1, 28, 39, 42, 39, 44, 32, 49])
tensor([ 1, 62, 73, 11,  0,  0,  3, 30, 62, 72])


**Bigram Model**

A bigram language model is a type of statistical language model that predicts the probability of a word in a sequence based on the previous word. It considers pairs of consecutive words (bigrams) and estimates the likelihood of encountering a specific word given the preceding word in a text or sentence.

In [ ]:
block_size=8
batch_size=4

x=train_data[:block_size+1]
y=train_data[1:block_size+1]

for t in range(block_size):
    context=x[:t+1]
    target=y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([80]) the target: 1
when input is tensor([80,  1]) the target: 1
when input is tensor([80,  1,  1]) the target: 28
when input is tensor([80,  1,  1, 28]) the target: 39
when input is tensor([80,  1,  1, 28, 39]) the target: 42
when input is tensor([80,  1,  1, 28, 39, 42]) the target: 39
when input is tensor([80,  1,  1, 28, 39, 42, 39]) the target: 44
when input is tensor([80,  1,  1, 28, 39, 42, 39, 44]) the target: 32


cuda is used for gpu based computation or training purpose.

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu
