<a href="https://colab.research.google.com/github/jaybhuvaa/LLM/blob/main/PyTorchOV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

randint=torch.randint(-1000,1000,(5,5))
randint

tensor([[-697,  789,  770,  786,   11],
        [ 249, -183, -263,    4,  721],
        [-423, -579,   37,  873, -681],
        [ 557,  331,  593, -951,  823],
        [ 907,  758,  876, -208,  751]])

In [ ]:
tensor=torch.tensor([[1.2,2.3],[3.5,8.3],[9.3,5.6]])
tensor

tensor([[1.2000, 2.3000],
        [3.5000, 8.3000],
        [9.3000, 5.6000]])

In [ ]:
zeros=torch.zeros((3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones=torch.ones((3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
inp=torch.empty(5,3)
inp

tensor([[-1.7048e-21,  3.3013e-41, -1.6998e-21],
        [ 3.3013e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  9.1084e-44]])

In [ ]:
arange=torch.arange(0,10)
arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#start,end,step
linespace=torch.linspace(3,10,10)
linespace

tensor([ 3.0000,  3.7778,  4.5556,  5.3333,  6.1111,  6.8889,  7.6667,  8.4444,
         9.2222, 10.0000])

In [ ]:
logsapce=torch.logspace(5,10,10)
logsapce

tensor([1.0000e+05, 3.5938e+05, 1.2915e+06, 4.6416e+06, 1.6681e+07, 5.9948e+07,
        2.1544e+08, 7.7426e+08, 2.7826e+09, 1.0000e+10])

In [ ]:
eye=torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
a=torch.empty((5,3),dtype=torch.int64)
a
empty_like=torch.empty_like(a)
empty_like

tensor([[    133197872614864,     133197872614864,                   0],
        [                  0,                   0, 7310593858020254331],
        [3616445622929465956, 6068653468605754676, 4122265038339323696],
        [6500156832662696238, 7309453675965983778, 8315168162784306286],
        [8367752027310484831, 7954801838398993778, 2459029315949324647]])

In [ ]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
import time
import numpy as np

start_time=time.time()
zeros=torch.zeros(1000,1000)
end_time=time.time()
print(end_time-start_time)


0.003531217575073242


In [ ]:
torch_rand1=torch.rand(1000,1000).to(device)
torch_rand2=torch.rand(1000,1000).to(device)
np_rand1=np.random.rand(1000,1000)
np_rand2=np.random.rand(1000,1000)

start_time=time.time()
rand=(torch_rand1 @ torch_rand2)
end_time=time.time()
print(end_time-start_time)

start_time=time.time()
rnd=np.multiply(np_rand1,np_rand2)
end_time=time.time()
print(end_time-start_time)

0.040517330169677734
0.004258394241333008


In [ ]:
torch_rand1=torch.rand(100,100,100,100).to(device)
torch_rand2=torch.rand(100,100,100,100).to(device)
np_rand1=np.random.rand(100,100,100,100)
np_rand2=np.random.rand(100,100,100,100)

start_time=time.time()
rand=(torch_rand1 @ torch_rand2)
end_time=time.time()
print(end_time-start_time)

start_time=time.time()
rnd=np.multiply(np_rand1,np_rand2)
end_time=time.time()
print(end_time-start_time)

0.7430455684661865
0.3199739456176758
