<a href="https://colab.research.google.com/github/jaybhuvaa/LLM/blob/main/torch_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import time


In [ ]:
%%time
start_time=time.time()
zeros=torch.zeros(1000000)
end_time=time.time()
print(end_time-start_time)

0.04147624969482422
CPU times: user 2.67 ms, sys: 2.97 ms, total: 5.64 ms
Wall time: 41.8 ms


In [ ]:
prob=torch.tensor([0.3,0.7])
samples=torch.multinomial(prob,10,True)
print(samples)

tensor([1, 0, 1, 0, 0, 1, 0, 1, 0, 1])


In [ ]:
tensor=torch.tensor([1,2,3,4])
out=torch.cat((tensor,torch.tensor([1,2,3,4])))
out

tensor([1, 2, 3, 4, 1, 2, 3, 4])

In [ ]:
out=torch.tril(torch.ones(3,3))
out

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [ ]:
out=torch.triu(torch.ones(3,3))
out

tensor([[1., 1., 1.],
        [0., 1., 1.],
        [0., 0., 1.]])

In [ ]:
out=torch.zeros(3,3).masked_fill(torch.tril(torch.ones(3,3))==0,float('-inf'))
out

tensor([[0., -inf, -inf],
        [0., 0., -inf],
        [0., 0., 0.]])

In [ ]:
torch.exp(out)

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [ ]:
ten=torch.zeros(1,2,3,4)
out=ten.transpose(0,1)
out.shape

torch.Size([2, 1, 3, 4])

In [ ]:
tensor1=torch.tensor([1,2,3,4])
tensor2=torch.tensor([1,2,3,4])
tensor3=torch.tensor([1,2,3,4])
tensor4=torch.tensor([1,2,3,4])
tensor5=torch.tensor([1,2,3,4])

stack_tensor=torch.stack((tensor1,tensor2,tensor3,tensor4,tensor5),dim=0)
stack_tensor

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])

In [ ]:
import torch.nn as nn
sample=torch.tensor([10.,10.,10.])
linear=nn.Linear(3,3,bias=False)

linear(sample)


tensor([ 1.5394,  8.2783, 11.5853], grad_fn=<SqueezeBackward4>)

In [ ]:
import torch.nn.functional as F
sample=torch.tensor([1.0,2.0,3.0])
ss=F.softmax(sample,dim=0)
print(ss)

tensor([0.0900, 0.2447, 0.6652])


In [ ]:
vocab_size=1000
embedding_dim=100
embedding=nn.Embedding(vocab_size,embedding_dim)
input=torch.LongTensor([1,2,3])
out=embedding(input)
print(out.shape)
out

torch.Size([3, 100])


tensor([[-0.3188,  0.2724,  0.2022,  0.3504, -0.5345,  1.2827,  0.0559, -0.4049,
          0.1924, -0.4955,  0.7555, -2.2290, -0.6144, -1.6914,  1.8126,  1.5992,
          1.5238,  0.3924,  0.1800, -1.3820, -2.2451,  0.6981, -0.9595,  0.2140,
         -0.6636,  0.0958,  0.1431, -0.5004,  1.8070, -0.5613, -1.7240,  0.4668,
          0.0822, -1.6110, -1.1304,  1.4920,  0.4709, -2.1562, -0.7147, -0.6285,
          0.0193,  1.2388, -0.7636, -0.7189,  0.0762,  0.4268, -0.2488, -2.0682,
          1.2732,  0.4685,  0.9396,  1.1498,  0.4666,  1.8424,  0.5319,  0.9796,
         -0.2448,  0.6371, -0.6433,  1.4445,  0.5137,  0.4625, -0.0411, -1.4152,
         -2.8529,  1.0772, -0.8817,  0.6905,  0.0153, -1.4749,  0.2928, -0.3639,
         -0.2473,  1.1078,  1.5041,  1.4531, -1.0697, -1.6445, -1.3428,  0.5093,
          0.4405,  1.0221, -0.3241, -0.5742, -1.1769,  0.4053, -2.6436, -0.6164,
         -2.4581,  1.6645,  0.8850, -0.9874,  0.4368, -1.2257,  1.3980,  0.8337,
          0.7476, -0.6371,  

In [6]:
mat1=([1,2,3],[4,5,6])
mat2=([7,8,9],[10,11,12],[1,2,3])
mat1=torch.tensor(mat1)
mat2=torch.tensor(mat2)
out=torch.matmul(mat1,mat2)

print(mat1 @ mat2)

tensor([[ 30,  36,  42],
        [ 84,  99, 114]])


In [11]:
int_64=torch.randint(10,(3,2))
float_32=torch.rand(2,3)
print(int_64)
print(float_32)
#print(int_64 @ float_32) cannot be multiplied

tensor([[8, 0],
        [0, 8],
        [5, 4]])
tensor([[0.3451, 0.0663, 0.5760],
        [0.9089, 0.7416, 0.3288]])
